/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'danda' at '11.2.17 10:07' with Gradle 2.14.1
 *
 * @author danda, @date 11.2.17 10:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
